const SITE_VERSION="2.2";
const state={manifest:null,data:null,category:"All",view:"compare",favorites:new Set(JSON.parse(localStorage.getItem("groceryFavorites")||"[]"))};
const $=s=>document.querySelector(s); const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
async function boot(){state.manifest=await fetch("data/manifest.json?v="+SITE_VERSION,{cache:"no-store"}).then(r=>{if(!r.ok)throw Error(`Manifest ${r.status}`);return r.json()});const options=state.manifest.weeks;$("#weekSelect").innerHTML=options.map(w=>`<option value="${esc(w.id)}">${esc(w.label)}</option>`).join("");await loadWeek(state.manifest.defaultWeek);wire()}
async function loadWeek(id){const item=state.manifest.weeks.find(w=>w.id===id);state.data=await fetch(item.file+"?v="+SITE_VERSION,{cache:"no-store"}).then(r=>{if(!r.ok)throw Error(`Data ${r.status}`);return r.json()});state.category="All";buildStoreFilter();render()}
function buildStoreFilter(){const stores=state.data?.stores||[];$("#storeFilter").innerHTML=`<option value="all">All stores</option>${stores.map(x=>`<option>${esc(x)}</option>`).join("")}`}
function wire(){$("#weekSelect").addEventListener("change",e=>loadWeek(e.target.value));["searchInput","storeFilter","matchFilter"].forEach(id=>$("#"+id).addEventListener(id==="searchInput"?"input":"change",render));$("#resetButton").onclick=()=>{$("#searchInput").value="";$("#storeFilter").value="all";$("#matchFilter").value="all";state.category="All";render()};document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{state.view=b.dataset.view;renderViews()});$("#themeButton").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("groceryTheme",document.body.classList.contains("dark")?"dark":"light")};if(localStorage.getItem("groceryTheme")==="dark")document.body.classList.add("dark")}
function filters(){return{q:$("#searchInput").value.trim().toLowerCase(),store:$("#storeFilter").value,match:$("#matchFilter").value}}
function visibleDeals(){const f=filters();return state.data.deals.filter(x=>x.displayReady!==false&&(state.category==="All"||x.department===state.category)&&(f.store==="all"||x.store===f.store)&&(`${x.productName} ${x.brand||""} ${x.department||""} ${x.exactAdWording||""} ${x.promotionType||""} ${x.packageSize||""}`.toLowerCase().includes(f.q)))}
function requirements(x){const req=[];if(x.loyaltyRequired)req.push('<span class="req loyalty">Loyalty card</span>');if(x.digitalCouponRequired)req.push('<span class="req">Digital coupon</span>');if(x.minimumPurchase)req.push(`<span class="req">${esc(x.minimumPurchase)}</span>`);if(x.purchaseLimit)req.push(`<span class="req">Limit ${esc(x.purchaseLimit)}</span>`);(x.dataNotices||[]).forEach(n=>req.push(`<span class="req notice">${esc(n)}</span>`));return req.join('')}
function productLabel(x){const brand=(x.brand||'').trim();const name=(x.productName||'').trim();if(brand&&name.toLowerCase().startsWith(brand.toLowerCase()))return name;return [brand,name].filter(Boolean).join(' ')||x.exactAdWording||'Advertised item'}
function norm(v){return String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function matchQuality(list){const brands=[...new Set(list.map(x=>norm(x.brand)).filter(Boolean))];const names=[...new Set(list.map(x=>norm(x.productName)).filter(Boolean))];const labels=[...new Set(list.map(x=>norm(productLabel(x))).filter(Boolean))];const units=[...new Set(list.map(x=>x.normalizedUnit).filter(Boolean))];if(labels.length===1&&units.length===1)return'exact';if(brands.length===1&&brands.length>0&&units.length===1)return'same-brand';return'category'}
function comparisonTitle(g,list,quality){if(quality==='exact')return productLabel(list[0]);if(quality==='same-brand')return `${list[0].brand||''} ${g?.name||list[0].productName}`.trim();return g?.name||list[0].department||'Category comparison'}
function comparisons(){const f=filters(),groups=new Map();state.data.deals.filter(x=>x.displayReady!==false&&x.comparisonReady&&typeof x.normalizedUnitPrice==="number").forEach(x=>{if(!groups.has(x.comparisonGroupId))groups.set(x.comparisonGroupId,[]);groups.get(x.comparisonGroupId).push(x)});return [...groups.entries()].map(([id,items])=>{const byStore={};items.forEach(x=>{if(!byStore[x.store]||x.normalizedUnitPrice<byStore[x.store].normalizedUnitPrice)byStore[x.store]=x});const list=Object.values(byStore);if(list.length<2)return null;list.sort((a,b)=>a.normalizedUnitPrice-b.normalizedUnitPrice);const g=state.data.comparisonGroups.find(z=>z.comparisonGroupId===id);const quality=matchQuality(list);const sameUnit=list.every(x=>x.normalizedUnit===list[0].normalizedUnit);const canNameWinner=(quality==='exact'||quality==='same-brand')&&sameUnit;return{id,item:comparisonTitle(g,list,quality),groupName:g?.name||'',category:g?.department||list[0].department,winner:canNameWinner?list[0].store:null,unit:list[0].normalizedUnit,items:list,quality,sameUnit,canNameWinner}}).filter(Boolean).filter(x=>(state.category==="All"||x.category===state.category)&&(f.match==="all"||x.quality===f.match)&&(f.store==="all"||x.items.some(i=>i.store===f.store))&&(`${x.item} ${x.groupName} ${x.category} ${x.items.map(i=>`${i.store} ${productLabel(i)} ${i.exactAdWording||''} ${i.packageSize||''}`).join(' ')}`.toLowerCase().includes(f.q)))}
function renderComparison(x,stores){const available=new Map(x.items.map(i=>[i.store,i]));const second=x.items[1];const savings=x.winner&&second?second.normalizedUnitPrice-x.items[0].normalizedUnitPrice:null;const cards=stores.map(store=>{const i=available.get(store);if(!i)return `<div class="store-price unavailable"><span>${esc(store)}</span><strong>Not advertised</strong><small>No matching sale found this week</small></div>`;return `<div class="store-price ${i.store===x.winner?'winner':''}"><div class="store-price-head"><span>${esc(i.store)}</span>${i.store===x.winner?'<b class="best-tag">BEST PRICE</b>':''}</div><h5>${esc(productLabel(i))}</h5><div class="item-detail">${esc(i.exactAdWording||i.productName)}</div><div class="size-line">${i.packageSize?`Size: <b>${esc(i.packageSize)}</b>`:'Size not listed in ad'}</div><strong class="ad-price">${esc(i.advertisedPrice)}</strong><small>${money(i.normalizedUnitPrice)} per ${esc(i.normalizedUnit||'unit')}</small><div class="requirements">${requirements(i)}</div></div>`}).join('');const qualityLabels={exact:'Exact product match','same-brand':'Same brand comparison',category:'Similar category products'};const label=x.canNameWinner?`${esc(x.winner)} wins`:'No exact winner';let note;if(x.quality==='exact')note=`Exact product comparison using normalized ${esc(x.unit)} pricing.${savings>0?` ${esc(x.winner)} is ${money(savings)} per ${esc(x.unit)} below the next-lowest store.`:''}`;else if(x.quality==='same-brand')note=`Same-brand comparison using normalized ${esc(x.unit)} pricing.${savings>0?` ${esc(x.winner)} is ${money(savings)} per ${esc(x.unit)} below the next-lowest store.`:''}`;else note='These are similar products in the same category, not identical items. Prices are shown for discovery without declaring a winner.';return `<article class="comparison"><div class="comparison-top"><div><h4>${esc(x.item)}</h4>${x.groupName&&x.groupName!==x.item?`<div class="group-label">Category: ${esc(x.groupName)}</div>`:''}<span class="match quality-${x.quality}">${qualityLabels[x.quality]}</span></div><span class="winner-chip ${x.canNameWinner?'':'neutral'}">${label}</span></div><div class="prices dynamic-prices four-store-prices">${cards}</div><p class="note">${note}</p></article>`}
function render(){const d=state.data,stores=d.stores||[];$("#weekLabel").textContent=d.dataWeek.label;$("#coverageText").textContent=`${d.metadata.totalDeals} deals extracted from ${stores.length} store circulars using the master workbook.`;$("#circularLinks").innerHTML=d.circulars.map(c=>`<a class="circular-link" href="${esc(c.url||'#')}" target="_blank" rel="noopener noreferrer"><span><b>${esc(c.store)}</b><small>${esc(c.startDate)} through ${esc(c.endDate)} · ${c.dealCount} deals</small></span><span>↗</span></a>`).join("");$("#sourceStatus").textContent="Master workbook production data";$("#sourceStatusDetail").textContent=`Loaded ${d.metadata.totalDeals} deal rows, ${d.metadata.productCount} products and ${d.metadata.comparisonGroupCount} comparison groups. Routine ad conditions are handled automatically; only ${d.metadata.internalReviewCount||0} item(s) require internal review.`;
const cats=["All",...new Set(d.deals.map(x=>x.department||"Other"))];$("#categoryRow").innerHTML=cats.map(c=>`<button data-cat="${esc(c)}" class="${c===state.category?'active':''}">${esc(c)}</button>`).join("");$("#categoryRow").querySelectorAll("button").forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;render()});
const comps=comparisons(),winnerEligible=comps.filter(x=>x.winner),wins=winnerEligible.reduce((a,x)=>(a[x.winner]=(a[x.winner]||0)+1,a),{}),win=Object.entries(wins).sort((a,b)=>b[1]-a[1])[0];$("#overallWinner").textContent=win?.[0]||"No clear winner";$("#winnerReason").textContent=win?`${win[1]} exact or same-brand wins using normalized unit prices.`:"Category comparisons are shown without naming a false winner.";
const counts=Object.fromEntries(stores.map(s=>[s,d.deals.filter(x=>x.store===s).length]));$("#statGrid").innerHTML=[["Weekly deals",d.metadata.totalDeals,"All advertised offers"],["Giant deals",counts.Giant||0,"Visible in All Deals and eligible comparisons"],["Comparisons",comps.length,"Exact, same-brand and category matches"],["Stores",stores.length,stores.join(" · ")]].map(x=>`<article class="stat"><span>${x[0]}</span><strong>${x[1]}</strong><small>${esc(x[2])}</small></article>`).join("");
$("#comparisonCount").textContent=`${comps.length} shown`;$("#comparisonList").innerHTML=comps.map(x=>renderComparison(x,stores)).join("")||`<p class="empty">No comparisons match those filters.</p>`;
const deals=visibleDeals();$("#dealCount").textContent=`${deals.length} shown`;$("#dealGrid").innerHTML=deals.map(dealCard).join("")||`<p class="empty">No deals match those filters.</p>`;bindHearts("#dealGrid");const plan=d.deals.filter(x=>x.displayReady!==false&&x.comparisonReady&&typeof x.normalizedUnitPrice==='number').sort((a,b)=>(a.normalizedUnitPrice??9999)-(b.normalizedUnitPrice??9999));$("#planGrid").innerHTML=stores.map(store=>{const items=plan.filter(x=>x.store===store).slice(0,8);return `<article class="store-plan"><h4><span>${esc(store)}</span><span>${items.length} buys</span></h4><ul>${items.map(x=>`<li>${esc(productLabel(x))}${x.packageSize?` (${esc(x.packageSize)})`:''} — <b>${esc(x.advertisedPrice)}</b></li>`).join("")}</ul></article>`}).join("");renderFavorites();renderViews()}
function money(v){return typeof v==='number'?`$${v.toFixed(v<1?3:2)}`:"—"}
function dealCard(x){const id=x.dealId,saved=state.favorites.has(id);return `<article class="deal"><div class="deal-head"><span class="store-pill">${esc(x.store)}</span><button class="heart ${saved?'saved':''}" data-id="${esc(id)}">${saved?'♥':'♡'}</button></div><h4>${esc(productLabel(x))}</h4><small>${esc(x.exactAdWording||'')}${x.packageSize?` · ${esc(x.packageSize)}`:''}</small><div class="promo">${esc(x.promotionType||'Weekly deal')}${x.promotionDetail?` · ${esc(x.promotionDetail)}`:''}</div><div class="price">${esc(x.advertisedPrice)}</div>${typeof x.normalizedUnitPrice==='number'?`<div class="unit-price">${money(x.normalizedUnitPrice)} per ${esc(x.normalizedUnit||'unit')}</div>`:''}<div class="requirements">${requirements(x)}</div><div class="fineprint">Valid ${esc(x.adStart)}–${esc(x.adEnd)} · ${esc(x.sourcePage)}</div>${x.internalReviewRequired?`<div class="review-note">Internal verification needed: ${esc(x.reviewReason||'verify source wording')}</div>`:''}</article>`}
function bindHearts(sel){$(sel).querySelectorAll('.heart').forEach(b=>b.onclick=()=>toggleFavorite(b.dataset.id))}function toggleFavorite(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem('groceryFavorites',JSON.stringify([...state.favorites]));render()}function renderFavorites(){const list=state.data.deals.filter(x=>state.favorites.has(x.dealId));$("#favoriteGrid").innerHTML=list.map(dealCard).join('');bindHearts('#favoriteGrid');$("#favoriteEmpty").classList.toggle('hidden',list.length>0)}function renderViews(){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===state.view));$("#"+state.view+"View").classList.add('active')}
boot().catch(err=>{document.body.innerHTML=`<main><h2>Dashboard could not load</h2><p>${esc(err.message)}</p><p>Open it through GitHub Pages or a local web server rather than directly as a file.</p></main>`});
